
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { HelpCircle, Home } from 'lucide-react';
import { 
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQ = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="bg-[#1A2A38] text-white py-4">
        <div className="container mx-auto px-4 flex justify-between items-center">
          <div className="flex items-center">
            <img 
              src="/lovable-uploads/1dc005c5-1f18-4598-92dc-030b0afec31f.png" 
              alt="Pro Net Solutions Logo" 
              className="h-8 mr-2" 
            />
            <span className="text-xl font-bold">Pro Net Solutions</span>
          </div>
          <div className="space-x-4">
            <Button 
              variant="link" 
              className="text-white" 
              onClick={() => navigate('/')}
            >
              <Home className="mr-2 h-4 w-4" />
              Back to Home
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center mb-8">
            <HelpCircle className="h-10 w-10 text-[#4CD3C8] mr-3" />
            <h1 className="text-4xl font-bold">Frequently Asked Questions</h1>
          </div>
          
          <div className="bg-card rounded-lg shadow-lg p-6 mb-8">
            <p className="text-muted-foreground mb-4">
              Find answers to the most common questions about Pro Net Solutions, our services, and how to get started.
            </p>
            
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger className="text-lg font-medium">
                  What is Pro Net Solutions?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  Pro Net Solutions is a multi-service platform that offers financial market education, fantasy gaming, and e-commerce solutions. We aim to empower individuals to build multiple streams of income through various channels.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-2">
                <AccordionTrigger className="text-lg font-medium">
                  How do I sign up for an account?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  You can sign up by clicking the "Sign Up" button on our homepage. Fill in the registration form with your details, agree to our terms of service, and submit. You'll receive a confirmation email to verify your account.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-3">
                <AccordionTrigger className="text-lg font-medium">
                  What trading signals do you offer?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  We offer trading signals for forex, cryptocurrency, and stocks. Our signals are generated by experienced traders and have a proven track record of success. They include entry points, take profit levels, stop loss levels, and market analysis.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-4">
                <AccordionTrigger className="text-lg font-medium">
                  How does the affiliate program work?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  Our affiliate program allows you to earn commissions by referring new members. You earn direct commissions for direct referrals and team overrides for your downline's activities. Our compensation plan includes multiple levels of earnings and performance bonuses.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-5">
                <AccordionTrigger className="text-lg font-medium">
                  What are EPins and how do they work?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  EPins are electronic pins that can be used to activate subscriptions or services. Affiliates can purchase EPins and distribute them to their team members or customers. EPins make it easy to manage subscriptions without needing online payment methods.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-6">
                <AccordionTrigger className="text-lg font-medium">
                  How can I withdraw my earnings?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  You can withdraw your earnings through the "Earnings Wallet" section of your dashboard. We support multiple withdrawal methods including bank transfers, cryptocurrency, and e-wallets. Withdrawals are processed within 1-3 business days.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-7">
                <AccordionTrigger className="text-lg font-medium">
                  Do you offer training for beginners?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  Yes, we offer comprehensive training for beginners through our education center. This includes video tutorials, webinars, e-books, and one-on-one mentorship sessions. All members have access to basic training, while premium members get additional resources.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-8">
                <AccordionTrigger className="text-lg font-medium">
                  What subscription plans do you offer?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  We offer several subscription plans ranging from basic to premium. Each plan includes different features and benefits, such as access to trading signals, educational resources, and marketing tools. You can view all available plans in the "Subscriptions" section.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-9">
                <AccordionTrigger className="text-lg font-medium">
                  How can I contact customer support?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  You can contact our customer support team through the "Support" section in your dashboard. We also offer support via email at support@pronetsolutions.com and through our social media channels. Our support team is available 24/7 to assist you.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-10">
                <AccordionTrigger className="text-lg font-medium">
                  Can I use Pro Net Solutions from any country?
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  Pro Net Solutions is available in most countries worldwide. However, certain services may be restricted in some countries due to local regulations. Please check our Terms of Service for specific country restrictions or contact our support team for more information.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>
          
          <div className="text-center">
            <p className="text-lg mb-4">Still have questions?</p>
            <Button 
              className="bg-[#4CD3C8] text-[#1A2A38] hover:bg-[#3cc3b8]"
              onClick={() => navigate('/contact')}
            >
              Contact Us
            </Button>
          </div>
        </div>
      </main>
      
      {/* Footer */}
      <footer className="bg-[#1A2A38] text-white py-8">
        <div className="container mx-auto px-4 text-center">
          <div className="flex justify-center space-x-4 mb-4">
            <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="text-white hover:text-[#4CD3C8]">
              <Facebook className="h-5 w-5" />
              <span className="sr-only">Facebook</span>
            </a>
            <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" className="text-white hover:text-[#4CD3C8]">
              <Instagram className="h-5 w-5" />
              <span className="sr-only">Instagram</span>
            </a>
            <a href="https://twitter.com" target="_blank" rel="noopener noreferrer" className="text-white hover:text-[#4CD3C8]">
              <Twitter className="h-5 w-5" />
              <span className="sr-only">Twitter</span>
            </a>
            <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="text-white hover:text-[#4CD3C8]">
              <Linkedin className="h-5 w-5" />
              <span className="sr-only">LinkedIn</span>
            </a>
            <a href="https://youtube.com" target="_blank" rel="noopener noreferrer" className="text-white hover:text-[#4CD3C8]">
              <Youtube className="h-5 w-5" />
              <span className="sr-only">YouTube</span>
            </a>
          </div>
          <p>&copy; {new Date().getFullYear()} Pro Net Solutions. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default FAQ;
